export interface CountryCode {
  code: string;
  country: string;
  flag: string;
}

export const countryCodes: CountryCode[] = [
  { code: "+55", country: "Brasil", flag: "🇧🇷" },
  { code: "+1", country: "Estados Unidos", flag: "🇺🇸" },
  { code: "+1", country: "Canadá", flag: "🇨🇦" },
  { code: "+54", country: "Argentina", flag: "🇦🇷" },
  { code: "+56", country: "Chile", flag: "🇨🇱" },
  { code: "+57", country: "Colômbia", flag: "🇨🇴" },
  { code: "+51", country: "Peru", flag: "🇵🇪" },
  { code: "+598", country: "Uruguai", flag: "🇺🇾" },
  { code: "+595", country: "Paraguai", flag: "🇵🇾" },
  { code: "+591", country: "Bolívia", flag: "🇧🇴" },
  { code: "+593", country: "Equador", flag: "🇪🇨" },
  { code: "+58", country: "Venezuela", flag: "🇻🇪" },
  { code: "+594", country: "Guiana Francesa", flag: "🇬🇫" },
  { code: "+592", country: "Guiana", flag: "🇬🇾" },
  { code: "+597", country: "Suriname", flag: "🇸🇷" },
  { code: "+351", country: "Portugal", flag: "🇵🇹" },
  { code: "+34", country: "Espanha", flag: "🇪🇸" },
  { code: "+33", country: "França", flag: "🇫🇷" },
  { code: "+39", country: "Itália", flag: "🇮🇹" },
  { code: "+49", country: "Alemanha", flag: "🇩🇪" },
  { code: "+44", country: "Reino Unido", flag: "🇬🇧" },
  { code: "+31", country: "Holanda", flag: "🇳🇱" },
  { code: "+32", country: "Bélgica", flag: "🇧🇪" },
  { code: "+41", country: "Suíça", flag: "🇨🇭" },
  { code: "+43", country: "Áustria", flag: "🇦🇹" },
  { code: "+45", country: "Dinamarca", flag: "🇩🇰" },
  { code: "+46", country: "Suécia", flag: "🇸🇪" },
  { code: "+47", country: "Noruega", flag: "🇳🇴" },
  { code: "+358", country: "Finlândia", flag: "🇫🇮" },
  { code: "+353", country: "Irlanda", flag: "🇮🇪" },
  { code: "+354", country: "Islândia", flag: "🇮🇸" },
  { code: "+48", country: "Polônia", flag: "🇵🇱" },
  { code: "+420", country: "República Tcheca", flag: "🇨🇿" },
  { code: "+421", country: "Eslováquia", flag: "🇸🇰" },
  { code: "+36", country: "Hungria", flag: "🇭🇺" },
  { code: "+40", country: "Romênia", flag: "🇷🇴" },
  { code: "+359", country: "Bulgária", flag: "🇧🇬" },
  { code: "+385", country: "Croácia", flag: "🇭🇷" },
  { code: "+386", country: "Eslovênia", flag: "🇸🇮" },
  { code: "+381", country: "Sérvia", flag: "🇷🇸" },
  { code: "+382", country: "Montenegro", flag: "🇲🇪" },
  { code: "+387", country: "Bósnia e Herzegovina", flag: "🇧🇦" },
  { code: "+389", country: "Macedônia do Norte", flag: "🇲🇰" },
  { code: "+355", country: "Albânia", flag: "🇦🇱" },
  { code: "+30", country: "Grécia", flag: "🇬🇷" },
  { code: "+90", country: "Turquia", flag: "🇹🇷" },
  { code: "+7", country: "Rússia", flag: "🇷🇺" },
  { code: "+380", country: "Ucrânia", flag: "🇺🇦" },
  { code: "+375", country: "Belarus", flag: "🇧🇾" },
  { code: "+373", country: "Moldova", flag: "🇲🇩" },
  { code: "+372", country: "Estônia", flag: "🇪🇪" },
  { code: "+371", country: "Letônia", flag: "🇱🇻" },
  { code: "+370", country: "Lituânia", flag: "🇱🇹" },
  { code: "+86", country: "China", flag: "🇨🇳" },
  { code: "+81", country: "Japão", flag: "🇯🇵" },
  { code: "+82", country: "Coreia do Sul", flag: "🇰🇷" },
  { code: "+91", country: "Índia", flag: "🇮🇳" },
  { code: "+62", country: "Indonésia", flag: "🇮🇩" },
  { code: "+60", country: "Malásia", flag: "🇲🇾" },
  { code: "+65", country: "Singapura", flag: "🇸🇬" },
  { code: "+66", country: "Tailândia", flag: "🇹🇭" },
  { code: "+84", country: "Vietnã", flag: "🇻🇳" },
  { code: "+63", country: "Filipinas", flag: "🇵🇭" },
  { code: "+880", country: "Bangladesh", flag: "🇧🇩" },
  { code: "+94", country: "Sri Lanka", flag: "🇱🇰" },
  { code: "+977", country: "Nepal", flag: "🇳🇵" },
  { code: "+92", country: "Paquistão", flag: "🇵🇰" },
  { code: "+93", country: "Afeganistão", flag: "🇦🇫" },
  { code: "+98", country: "Irã", flag: "🇮🇷" },
  { code: "+964", country: "Iraque", flag: "🇮🇶" },
  { code: "+962", country: "Jordânia", flag: "🇯🇴" },
  { code: "+961", country: "Líbano", flag: "🇱🇧" },
  { code: "+963", country: "Síria", flag: "🇸🇾" },
  { code: "+972", country: "Israel", flag: "🇮🇱" },
  { code: "+970", country: "Palestina", flag: "🇵🇸" },
  { code: "+966", country: "Arábia Saudita", flag: "🇸🇦" },
  { code: "+971", country: "Emirados Árabes Unidos", flag: "🇦🇪" },
  { code: "+973", country: "Bahrein", flag: "🇧🇭" },
  { code: "+974", country: "Catar", flag: "🇶🇦" },
  { code: "+965", country: "Kuwait", flag: "🇰🇼" },
  { code: "+968", country: "Omã", flag: "🇴🇲" },
  { code: "+967", country: "Iêmen", flag: "🇾🇪" },
  { code: "+20", country: "Egito", flag: "🇪🇬" },
  { code: "+27", country: "África do Sul", flag: "🇿🇦" },
  { code: "+234", country: "Nigéria", flag: "🇳🇬" },
  { code: "+254", country: "Quênia", flag: "🇰🇪" },
  { code: "+255", country: "Tanzânia", flag: "🇹🇿" },
  { code: "+256", country: "Uganda", flag: "🇺🇬" },
  { code: "+233", country: "Gana", flag: "🇬🇭" },
  { code: "+225", country: "Costa do Marfim", flag: "🇨🇮" },
  { code: "+221", country: "Senegal", flag: "🇸🇳" },
  { code: "+212", country: "Marrocos", flag: "🇲🇦" },
  { code: "+213", country: "Argélia", flag: "🇩🇿" },
  { code: "+216", country: "Tunísia", flag: "🇹🇳" },
  { code: "+218", country: "Líbia", flag: "🇱🇾" },
  { code: "+251", country: "Etiópia", flag: "🇪🇹" },
  { code: "+61", country: "Austrália", flag: "🇦🇺" },
  { code: "+64", country: "Nova Zelândia", flag: "🇳🇿" },
  { code: "+679", country: "Fiji", flag: "🇫🇯" },
  { code: "+685", country: "Samoa", flag: "🇼🇸" },
  { code: "+676", country: "Tonga", flag: "🇹🇴" },
  { code: "+687", country: "Nova Caledônia", flag: "🇳🇨" },
  { code: "+689", country: "Polinésia Francesa", flag: "🇵🇫" },
  { code: "+506", country: "Costa Rica", flag: "🇨🇷" },
  { code: "+507", country: "Panamá", flag: "🇵🇦" },
  { code: "+502", country: "Guatemala", flag: "🇬🇹" },
  { code: "+503", country: "El Salvador", flag: "🇸🇻" },
  { code: "+504", country: "Honduras", flag: "🇭🇳" },
  { code: "+505", country: "Nicarágua", flag: "🇳🇮" },
  { code: "+501", country: "Belize", flag: "🇧🇿" },
  { code: "+52", country: "México", flag: "🇲🇽" },
  { code: "+53", country: "Cuba", flag: "🇨🇺" },
  { code: "+1", country: "Jamaica", flag: "🇯🇲" },
  { code: "+1", country: "Bahamas", flag: "🇧🇸" },
  { code: "+1", country: "Barbados", flag: "🇧🇧" },
  { code: "+1", country: "Trinidad e Tobago", flag: "🇹🇹" },
  { code: "+1809", country: "República Dominicana", flag: "🇩🇴" },
  { code: "+509", country: "Haiti", flag: "🇭🇹" },
];